package citysim;

public final class CalibrateWithCadyts {
    private CalibrateWithCadyts() {
    }

    public static void main(String[] args) {
        // TODO: Load scenarios/logan_square/config.xml, attach counts.xml, and configure
        // MATSim Cadyts integration once calibrated counts are generated by s4.
        throw new UnsupportedOperationException("TODO: implement Cadyts-integrated calibration run");
    }
}
